<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.12.2" name="Premade_houses" tilewidth="32" tileheight="32" tilecount="4096" columns="64">
 <image source="../../buildings/Premade_houses.png" width="2048" height="2048"/>
 <tile id="0" type="above"/>
 <tile id="1" type="above"/>
 <tile id="2" type="above"/>
 <tile id="3" type="above"/>
 <tile id="4" type="above"/>
 <tile id="5" type="above"/>
 <tile id="6" type="above"/>
 <tile id="7" type="above"/>
 <tile id="8" type="above"/>
 <tile id="9" type="above"/>
 <tile id="10" type="above"/>
 <tile id="11" type="above"/>
 <tile id="12" type="above"/>
 <tile id="13" type="above"/>
 <tile id="64" type="above"/>
 <tile id="65" type="above"/>
 <tile id="66" type="above"/>
 <tile id="67" type="above"/>
 <tile id="68" type="above"/>
 <tile id="69" type="above"/>
 <tile id="70" type="above"/>
 <tile id="71" type="above"/>
 <tile id="72" type="above"/>
 <tile id="73" type="above"/>
 <tile id="74" type="above"/>
 <tile id="75" type="above"/>
 <tile id="76" type="above"/>
 <tile id="77" type="above"/>
 <tile id="128" type="above"/>
 <tile id="129" type="above"/>
 <tile id="130" type="above"/>
 <tile id="131" type="above"/>
 <tile id="132" type="above"/>
 <tile id="133" type="above"/>
 <tile id="134" type="above"/>
 <tile id="135" type="above"/>
 <tile id="136" type="above"/>
 <tile id="137" type="above"/>
 <tile id="138" type="above"/>
 <tile id="139" type="above"/>
 <tile id="140" type="above"/>
 <tile id="141" type="above"/>
 <tile id="192" type="above"/>
 <tile id="193" type="above"/>
 <tile id="194" type="above"/>
 <tile id="195" type="above"/>
 <tile id="196" type="above"/>
 <tile id="197" type="above"/>
 <tile id="198" type="above"/>
 <tile id="199" type="above"/>
 <tile id="200" type="above"/>
 <tile id="201" type="above"/>
 <tile id="202" type="above"/>
 <tile id="203" type="above"/>
 <tile id="204" type="above"/>
 <tile id="205" type="above"/>
 <tile id="256" type="above"/>
 <tile id="257" type="above"/>
 <tile id="258" type="above"/>
 <tile id="259" type="above"/>
 <tile id="260" type="above"/>
 <tile id="261" type="above"/>
 <tile id="262" type="above"/>
 <tile id="263" type="above"/>
 <tile id="264" type="above"/>
 <tile id="265" type="above"/>
 <tile id="266" type="above"/>
 <tile id="267" type="above"/>
 <tile id="268" type="above"/>
 <tile id="269" type="above"/>
 <tile id="320" type="above"/>
 <tile id="321" type="above"/>
 <tile id="322" type="above"/>
 <tile id="323" type="above"/>
 <tile id="324" type="above"/>
 <tile id="325" type="above"/>
 <tile id="326" type="above"/>
 <tile id="327" type="above"/>
 <tile id="328" type="above"/>
 <tile id="329" type="above"/>
 <tile id="330" type="above"/>
 <tile id="331" type="above"/>
 <tile id="332" type="above"/>
 <tile id="333" type="above"/>
 <tile id="384" type="above"/>
 <tile id="385" type="above"/>
 <tile id="386" type="above"/>
 <tile id="387" type="above"/>
 <tile id="388" type="above"/>
 <tile id="389" type="above"/>
 <tile id="390" type="above"/>
 <tile id="391" type="above"/>
 <tile id="392" type="above"/>
 <tile id="393" type="above"/>
 <tile id="394" type="above"/>
 <tile id="395" type="above"/>
 <tile id="396" type="above"/>
 <tile id="397" type="above"/>
 <tile id="448" type="above"/>
 <tile id="449" type="above"/>
 <tile id="450" type="above"/>
 <tile id="451" type="above"/>
 <tile id="452" type="above"/>
 <tile id="453" type="above"/>
 <tile id="454" type="above"/>
 <tile id="455" type="above"/>
 <tile id="456" type="above"/>
 <tile id="457" type="above"/>
 <tile id="458" type="above"/>
 <tile id="459" type="above"/>
 <tile id="460" type="above"/>
 <tile id="461" type="above"/>
 <tile id="512" type="above"/>
 <tile id="513" type="above"/>
 <tile id="514" type="above"/>
 <tile id="515" type="above"/>
 <tile id="516" type="above"/>
 <tile id="517" type="above"/>
 <tile id="518" type="above"/>
 <tile id="519" type="above"/>
 <tile id="520" type="above"/>
 <tile id="521" type="above"/>
 <tile id="522" type="above"/>
 <tile id="523" type="above"/>
 <tile id="524" type="above"/>
 <tile id="525" type="above"/>
 <tile id="576" type="above"/>
 <tile id="577" type="above"/>
 <tile id="578" type="above"/>
 <tile id="579" type="above"/>
 <tile id="580" type="above"/>
 <tile id="581" type="above"/>
 <tile id="582" type="above"/>
 <tile id="583" type="above"/>
 <tile id="584" type="above"/>
 <tile id="585" type="above"/>
 <tile id="586" type="above"/>
 <tile id="587" type="above"/>
 <tile id="588" type="above"/>
 <tile id="589" type="above"/>
 <tile id="640" type="above"/>
 <tile id="641" type="above"/>
 <tile id="642" type="above"/>
 <tile id="643" type="above"/>
 <tile id="644" type="above"/>
 <tile id="645" type="above"/>
 <tile id="646" type="above"/>
 <tile id="647" type="above"/>
 <tile id="648" type="above"/>
 <tile id="649" type="above"/>
 <tile id="650" type="above"/>
 <tile id="651" type="above"/>
 <tile id="652" type="above"/>
 <tile id="653" type="above"/>
 <tile id="704" type="above"/>
 <tile id="705" type="above"/>
 <tile id="706" type="above"/>
 <tile id="707" type="above"/>
 <tile id="708" type="above"/>
 <tile id="709" type="above"/>
 <tile id="710" type="above"/>
 <tile id="711" type="above"/>
 <tile id="712" type="above"/>
 <tile id="713" type="above"/>
 <tile id="714" type="above"/>
 <tile id="715" type="above"/>
 <tile id="716" type="above"/>
 <tile id="717" type="above"/>
 <tile id="768" type="above"/>
 <tile id="769" type="above"/>
 <tile id="770" type="above"/>
 <tile id="771" type="above"/>
 <tile id="772" type="above"/>
 <tile id="773" type="above"/>
 <tile id="774" type="above"/>
 <tile id="775" type="above"/>
 <tile id="776" type="above"/>
 <tile id="777" type="above"/>
 <tile id="778" type="above"/>
 <tile id="779" type="above"/>
 <tile id="780" type="above"/>
 <tile id="781" type="above"/>
</tileset>
